# Generated by Django 5.2.7 on 2025-10-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('moeda_base', models.CharField(default='USD', max_length=3)),
                ('moeda_tgt', models.CharField(max_length=3)),
                ('taxa', models.FloatField()),
            ],
            options={
                'ordering': ['data'],
                'unique_together': {('data', 'moeda_tgt')},
            },
        ),
    ]
